version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "49160:8080"
    env_file:
      - ./environment/development.env
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 300M
networks:
  backend:
