version: "3.9"

services:
  api:
    image: node:14-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: npm run debug
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "49160:8080"
      - "9229:9229"
    env_file:
      - ./environment/development.env
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 300M
networks:
  backend:
