version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /home/node/app
    user: node
    entrypoint: "/bin/sh -c"
    ports:
      - "8080:8080"
      - "9229:9229"
    env_file:
      - .env
    networks:
      - backend
networks:
  backend:
